project:
  type: book

book:
  title: "Mappeeksamen IDR4000"
  author: "kandidat 103"
  date: "2025-02-17"
  chapters:
    - index.qmd
    - 01-reliabilitet.qmd
    - 02-regression-models.qmd
    - 03-statistical-inference.qmd
    - 04-study-design.qmd
    - 05-repeated-measurements.qmd
    - 06-vitenskapsteori.qmd
    - 07-laboratory-report.qmd
    - references.qmd


format: pdf



