# Introduksjon til mappetemplat og Lærinsgrefleksjon {.unnumbered}

## Forord 

Ønsker å takke Daniel for god hjelp og veiledning, innlæring av Rstudio viste seg og være både svært utfordrende og frustrerende for en ung kar som ikke engang forsto seg på Excel. 

Ønsker også og rette en takk til, Jens-Henrik, Anders, Sivert og Ole-Kristian for sammarbeid i lab-undervisningen, med sammarbeid av labrapporter og assignement 1-2. Det har vært en lærerik og morsom opplevelse.

Lenke til repository: https://github.com/Adrianhaslum/mappeeksamen.git

Mappeeksamen består av følgende deler: 

- Rapport: "Deskriptiv statistikk, reliabilitet og validitet og verktøy for reproduserbar vitenskap".
- Laborasjonsrapport fra molekylærlabb
- Arbeidskrav i vitenskapsteori
- Rapport: "Statistisk inferens, statistiske modeller og statistisk styrke"
- Rapport: "Studiedesign"
- Rapport: "Analyse av eksperimenter med repeterte målinger"

I templatet organiseres hver del som et kapittel. 

Referanser finner du sist i dokumenetet 