# References 

Holmen, H. A. (5. mars. 2024). Induksjonsproblemet
Hentet fra: https://snl.no/induksjonsproblemet 

Vassend, O. (2024). «Vitenskapsfilosofi dag 2». Forelesning ved Høgskolen i innlandet. 

Linder. J. (14. nov. 2019). Kvantemekanikk.
Hentet fra: https://snl.no/kvantemekanikk 
 
Lasevicius, T., Ugrinowitsch, C., Schoenfeld, B. J., Roschel, H., Tavares, L. D., De Souza, E. O., Laurentino, G., & Tricoli, V. (2018). Effects of different intensities of resistance training with equated volume load on muscle strength and hypertrophy. European journal of sport science, 18(6), 772–780. https://doi.org/10.1080/17461391.2018.1450898 
 
Fry A. C. (2004). The role of resistance exercise intensity on muscle fibre adaptations. Sports medicine (Auckland, N.Z.), 34(10), 663–679. https://doi.org/10.2165/00007256-200434100-00004 
 
 Grgic, J., Schoenfeld, B. J., Orazem, J., & Sabol, F. (2022). Effects of resistance training performed to repetition failure or non-failure on muscular strength and hypertrophy: A systematic review and meta-analysis. Journal of sport and health science, 11(2), 202–211. https://doi.org/10.1016/j.jshs.2021.01.007

Kraemer, W. J., & Ratamess, N. A. (2004). Fundamentals of resistance training: progression and exercise prescription. Medicine & science in sports & exercise, 36(4), 674-688.

Krieger, James W. Single vs. Multiple Sets of Resistance Exercise for Muscle Hypertrophy: A Meta-Analysis. Journal of Strength and Conditioning Research 24(4):p 1150-1159, April 2010. | DOI: 10.1519/JSC.0b013e3181d4d436

Raastad, T., Paulsen, G., Refsnes, P. E., Rønnestad, B. R., & Wisnes, A. R. (2013). Styrketrening – I teori og praksis (3. utg.). Gyldendal Akademisk.

Refalo, M. C., Helms, E. R., Robinson, Z. P., Hamilton, D. L., & Fyfe, J. J. (2024). Similar muscle hypertrophy following eight weeks of resistance training to momentary muscular failure or with repetitions-in-reserve in resistance-trained individuals. Journal of sports sciences, 42(1), 85–101. https://doi.org/10.1080/02640414.2024.2321021

Ruple, B. A., Plotkin, D. L., Smith, M. A., Godwin, J. S., Sexton, C. L., McIntosh, M. C., Kontos, N. J., Beausejour, J. P., Pagan, J. I., Rodriguez, J. P., Sheldon, D., Knowles, K. S., Libardi, C. A., Young, K. C., Stock, M. S., & Roberts, M. D. (2023). The effects of resistance training to near failure on strength, hypertrophy, and motor unit adaptations in previously trained adults. Physiological reports, 11(9), e15679. https://doi.org/10.14814/phy2.15679

Schoenfeld B. J. (2010). Squatting kinematics and kinetics and their application to exercise performance. Journal of strength and conditioning research, 24(12), 3497–3506. https://doi.org/10.1519/JSC.0b013e3181bac2d7

Schoenfeld, B. J., Ogborn, D., & Krieger, J. W. (2016). Dose-response relationship between weekly resistance training volume and increases in muscle mass: A systematic review and meta-analysis. Journal of Sports Sciences, 35(11), 1073–1082. https://doi.org/10.1080/02640414.2016.1210197

Spiegelhalter, D. J. 2019. The Art of Statistics : How to Learn from Data. Book. First US edition. New York: Basic Books.
Tanner, R. K., and C. J. Gore. 2012. Physiological Tests for Elite Athletes 2nd Edition. Book. Human Kinetics. https://books.google.no/books?id=0OPIiMks58MC.

Hopkins, W. G. 2000. “Measures of Reliability in Sports Medicine and Science.” Journal Article. Sports Med 30 (1): 1–15. http://www.ncbi.nlm.nih.gov/pubmed/10907753.

Kuang, J., X. Yan, A. J. Genders, C. Granata, and D. J. Bishop. 2018. “An Overview of Technical Considerations When Using Quantitative Real-Time PCR Analysis of Gene Expression in Human Exercise Research.” PLoS One 13 (5): e0196438. https://doi.org/10.1371/journal.pone.0196438.

